### ISSUE TITLE
issue on step 18 - same sequences classified as both mate and non-mate

### ISSUE THREAD

**Issue by silasmellor** [pselva7/PlantMATEsClassification#1]
Hi, first of all thanks for a very useful script. I am looking at some MATE transporters and was hoping to use it to get an overview, but on running the script it doesnt produce the expected output. I tried running with the test files you provide and it runs fine, but it seems to classify my sequences as both MATE and non-MATE in the 18.* output. When i look in 8.* i can see a list with different group/subgroup classifications for most of the input sequences. I am sure this is an easy fix, but i am not very experienced with .sh scripts so im hoping you could help me.

I have attached the folder containing the input file, edited script and resulting outputs.

Best,
Silas
[PiMATE_error.zip](https://github.com/pselva7/PlantMATEsClassification/files/11947669/PiMATE_error.zip)

**Comment by pselva7** [comment]
Hi Silas,
Thank you for raising the issue. I found carriage-return characters (^M) in your protein (i.e., .fasta) file, which causes the issue. Carriage return characters may present in the file while copying files from windows to unix. You can get more information at [https://unix.stackexchange.com/questions/32001/what-is-m-and-how-do-i-get-rid-of-it](url)

Anyhow, just try the following code, it will work:
1. First, we have to remove the carriage-return character using the following code.
sed -i -e "s/\r//g" pin_MATE_PF01554.fasta
2. Then, run ./PlantMATEsClassification.sh
This will return the results.

Attached the clean fasta file, log file and summary file for your reference.
[cleaned_pinMate.zip](https://github.com/pselva7/PlantMATEsClassification/files/11958467/cleaned_pinMate.zip)

Regards,
Panneerselvam K.,
